DROP TABLE "BFILE";
DROP TABLE "GUEST";
DROP TABLE "BOARD";
DROP TABLE "BOARDTYPE";
DROP TABLE "MEMBER";
DROP TABLE "BUSINESS_INFO";

CREATE TABLE "BUSINESS_INFO" (
	"BUSNO"	VARCHAR2(30)		NOT NULL,
	"BUSNAME"	VARCHAR2(100)		NOT NULL,
	"BUSCEONAME"	VARCHAR2(100)		NOT NULL,
	"BUSCERTIFICATION"	VARCHAR2(500)		NOT NULL
);
ALTER TABLE "BUSINESS_INFO" ADD CONSTRAINT "PK_BUSINESS_INFO" PRIMARY KEY (
	"BUSNO"
);
COMMENT ON COLUMN "BUSINESS_INFO"."BUSCERTIFICATION" IS '/resources/certification/';

CREATE TABLE "MEMBER" (
	"MID"	VARCHAR2(30)		NOT NULL,
	"MPWD"	VARCHAR2(20)		NOT NULL,
	"MNAME"	VARCHAR2(100)		NOT NULL,
	"MEMAIL"	VARCHAR2(100)		NOT NULL,
	"MENTRANCE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MAUTHCODE"	VARCHAR2(20)	DEFAULT 0	NOT NULL,
	"MCONSENT1"	NUMBER(3)	DEFAULT 0	NOT NULL,
	"MTYPE"	NUMBER(1)	DEFAULT 1	NOT NULL,
	"BUSNO"	VARCHAR2(30)
);
ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER2" PRIMARY KEY (
	"MID"
);
COMMENT ON COLUMN "MEMBER"."MID" IS '영문숫자!@^_ 최소6자이상';
COMMENT ON COLUMN "MEMBER"."MPWD" IS '영문숫자!@^_ 최소6자이상';
COMMENT ON COLUMN "MEMBER"."MEMAIL" IS '@.';
COMMENT ON COLUMN "MEMBER"."MAUTHCODE" IS '인증전=0,인증완료=1,인증절차중=그외인증코드전송후';
COMMENT ON COLUMN "MEMBER"."MCONSENT1" IS '선택1=1, 선택2=2, 선택12=3, 선택3=4, 선택123=7';
COMMENT ON COLUMN "MEMBER"."MTYPE" IS '관리자=0,일반회원=1,사업자회원=2';


CREATE TABLE "BOARDTYPE" (
	"BTYPE"	CHAR(1)		NOT NULL,
	"BTYPENAME"	VARCHAR2(60)		NOT NULL
);
ALTER TABLE "BOARDTYPE" ADD CONSTRAINT "PK_BOARDTYPE" PRIMARY KEY (
	"BTYPE"
);
COMMENT ON COLUMN "BOARDTYPE"."BTYPE" IS 'A:일반게시판,B=QNA';

CREATE TABLE "BOARD" (
	"BNO"	NUMBER		NOT NULL,
	"BTITLE"	VARCHAR2(300)		NOT NULL,
	"BCONTENT"	VARCHAR2(4000)		NOT NULL,
	"BDATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"BCNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BREF"	NUMBER		NOT NULL,
	"BRELEVEL"	NUMBER		NOT NULL,
	"BRESTEP"	NUMBER		NOT NULL,
	"BWRITER"	VARCHAR2(30)		NOT NULL,
	"BTYPE"	CHAR(1)		NOT NULL
);
ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BNO"
);
COMMENT ON COLUMN "BOARD"."BREF" IS 'BNO와동일하면 원본글,다르면답글';
COMMENT ON COLUMN "BOARD"."BRELEVEL" IS '원본글0 답글1, 답답글2';
COMMENT ON COLUMN "BOARD"."BRESTEP" IS '원본글1';
COMMENT ON COLUMN "BOARD"."BWRITER" IS '영문숫자!@^_ 최소6자이상';
COMMENT ON COLUMN "BOARD"."BTYPE" IS 'A:일반게시판,B=QNA';

CREATE TABLE "BFILE" (
	"BFILEPATH"	VARCHAR2(500)		NOT NULL,
	"BNO"	NUMBER		NOT NULL
);
ALTER TABLE "BFILE" ADD CONSTRAINT "PK_BFILE" PRIMARY KEY (
	"BFILEPATH",
	"BNO"
);
COMMENT ON COLUMN "BFILE"."BFILEPATH" IS '/resources/board/';

CREATE TABLE "GUEST" (
	"GEMAIL"	VARCHAR2(100)		NOT NULL,
	"GNAME"	VARCHAR2(100)		NOT NULL,
	"BNO"	NUMBER		NOT NULL,
	"GPWD"	VARCHAR2(20)		NOT NULL
);
ALTER TABLE "GUEST" ADD CONSTRAINT "PK_GUEST" PRIMARY KEY (
	"GEMAIL",
	"GNAME",
	"BNO"
);

--참조키설정
ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_BUSINESS_INFO_TO_MEMBER_1" FOREIGN KEY (
	"BUSNO"
)
REFERENCES "BUSINESS_INFO" (
	"BUSNO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"BWRITER"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARDTYPE_TO_BOARD_1" FOREIGN KEY (
	"BTYPE"
)
REFERENCES "BOARDTYPE" (
	"BTYPE"
);

ALTER TABLE "GUEST" ADD CONSTRAINT "FK_BOARD_TO_GUEST_1" FOREIGN KEY (
	"BNO"
)
REFERENCES "BOARD" (
	"BNO"
);

ALTER TABLE "BFILE" ADD CONSTRAINT "FK_BOARD_TO_BFILE_1" FOREIGN KEY (
	"BNO"
)
REFERENCES "BOARD" (
	"BNO"
);

